In [1]:
import json
import pandas as pd
from fosforml.model_manager.snowflakesession import get_session
my_session = get_session()

In [42]:
table_name = 'FINAL_DATA'
sf_df = my_session.sql("select * from {}".format(table_name))
df = sf_df.to_pandas()

In [43]:
df

,MEMBER_ID,MEMBER_NAME,MEMBER_DOB,MEMBER_EMPLOYMENT,MEMBER_GENDER,MEMBER_CITY_TOWN,MEMBER_STATE,MEMBER_CONTACT_VERIFIED,PORTFOLIO,INTITIAL_INVVESTMENT,ORG_INVST,TEMP_OPTIMIZED,EXPECTED_PORTFOLIO,INITIAL_INVESTMENT_STOCKS
0,MID000001,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,"['CCSO', 'MPJ', 'ABC', 'EG']",5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...","[1250.0, 1250.0, 1250.0, 1250.0]"
1,MID000002,Jade Strassner,1986-11-19,Curtin University,Female,Gladstone,Queensland,False,"['EG', 'ABC', 'ONH', 'MZNA', 'FWC', 'GMNA', 'T...",69000,"{'Initial Investment': '$69,000.00', 'Expected...","[{'Initial Investment': '$69,000.00', 'Expecte...","[263583247.83, 1586958889.8, 183033297.12, 9.1...","[7666.666666666667, 7666.666666666667, 7666.66..."
2,MID000003,Mari Candlish,1989-01-27,University of New England,Female,Walgett,New South Wales,True,"['MMM', 'PG', 'NTIC', 'EPF', 'SM', 'ALPA']",49000,"{'Initial Investment': '$49,000.00', 'Expected...","[{'Initial Investment': '$49,000.00', 'Expecte...","[132926565.44999999, 800312599.8000001, 923047...","[8166.666666666667, 8166.666666666667, 8166.66..."
3,MID000004,Serina Leto,1984-03-08,Griffith University,Female,Paynesville,Victoria,True,"['JJN', 'PG', 'AB', 'OOGGL', 'NTIC', 'MMM']",1000,"{'Initial Investment': '$1,000.00', 'Expected ...","[{'Initial Investment': '$1,000.00', 'Expected...","[55363.001, 333324.69800000003, 38444.2969, 1....","[166.66666666666666, 166.66666666666666, 166.6..."
4,MID000005,Brett Butzen,1970-01-23,La Trobe University,Male,Palmerston,Northern Territory,True,"['SM', 'JJN', 'ALPA', 'NTIC', 'HD', 'AB', 'MZNA']",5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...","[714.2857142857143, 714.2857142857143, 714.285..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,MID241996,Nu Ragel,1967-01-24,La Trobe University,Male,Urraween,Queensland,False,"['MTFS', 'MPJ', 'SM', 'OCST', 'NTIC', 'CCSO', ...",90000,"{'Initial Investment': '$90,000.00', 'Expected...","[{'Initial Investment': '$90,000.00', 'Expecte...","[448440308.09999996, 2699930052.0, 311398804.8...","[11250.0, 11250.0, 11250.0, 11250.0, 11250.0, ..."
99996,MID241997,Lucy Hoa,1973-04-30,University of New England,Male,Wilton,New South Wales,True,"['GS', 'JJN', 'HD']",5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...","[1666.6666666666667, 1666.6666666666667, 1666...."
99997,MID241998,Lucina Klimek,1991-07-03,Queensland University of Technology,Male,Vincentia,New South Wales,False,"['ONH', 'AB', 'GS']",1000,"{'Initial Investment': '$1,000.00', 'Expected ...","[{'Initial Investment': '$1,000.00', 'Expected...","[55363.001, 333324.69800000003, 38444.2969, 1....","[333.3333333333333, 333.3333333333333, 333.333..."
99998,MID241999,Maurine Dopico,1976-05-17,RMIT University,Male,Eden,New South Wales,False,"['MPJ', 'MZNA', 'FWC', 'HD', 'ALPA', 'OOGGL']",5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...","[833.3333333333334, 833.3333333333334, 833.333..."
99999,MID242000,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,"['MMM', 'PG', 'MZNA', 'EPF', 'HD', 'JJN', 'ABC']",80000,"{'Initial Investment': '$80,000.00', 'Expected...","[{'Initial Investment': '$80,000.00', 'Expecte...","[354323206.4, 2133278064.0, 246043500.0, 1.225...","[11428.57142857143, 11428.57142857143, 11428.5..."

In [44]:
import ast
# Function to explode the 'PORTFOLIO' and 'INITIAL_INVESTMENT_STOCKS' columns
def explode_columns(df, portfolio_col, investment_col):
    df[portfolio_col] = df[portfolio_col].apply(eval)  # Convert string representation of list to actual list
    df[investment_col] = df[investment_col].apply(eval)  # Convert string representation of list to actual list
    df = df.explode([portfolio_col, investment_col])
    return df

# Columns to be exploded
portfolio_col = 'PORTFOLIO'
investment_col = 'INITIAL_INVESTMENT_STOCKS'

# Explode the specified columns
df_exploded = explode_columns(df, portfolio_col, investment_col)

In [45]:
df_exploded

,MEMBER_ID,MEMBER_NAME,MEMBER_DOB,MEMBER_EMPLOYMENT,MEMBER_GENDER,MEMBER_CITY_TOWN,MEMBER_STATE,MEMBER_CONTACT_VERIFIED,PORTFOLIO,INTITIAL_INVVESTMENT,ORG_INVST,TEMP_OPTIMIZED,EXPECTED_PORTFOLIO,INITIAL_INVESTMENT_STOCKS
0,MID000001,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,CCSO,5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...",1250.0
0,MID000001,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,MPJ,5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...",1250.0
0,MID000001,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,ABC,5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...",1250.0
0,MID000001,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,EG,5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...",1250.0
1,MID000002,Jade Strassner,1986-11-19,Curtin University,Female,Gladstone,Queensland,False,EG,69000,"{'Initial Investment': '$69,000.00', 'Expected...","[{'Initial Investment': '$69,000.00', 'Expecte...","[263583247.83, 1586958889.8, 183033297.12, 9.1...",7666.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99999,MID242000,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,MZNA,80000,"{'Initial Investment': '$80,000.00', 'Expected...","[{'Initial Investment': '$80,000.00', 'Expecte...","[354323206.4, 2133278064.0, 246043500.0, 1.225...",11428.571429
99999,MID242000,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,EPF,80000,"{'Initial Investment': '$80,000.00', 'Expected...","[{'Initial Investment': '$80,000.00', 'Expecte...","[354323206.4, 2133278064.0, 246043500.0, 1.225...",11428.571429
99999,MID242000,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,HD,80000,"{'Initial Investment': '$80,000.00', 'Expected...","[{'Initial Investment': '$80,000.00', 'Expecte...","[354323206.4, 2133278064.0, 246043500.0, 1.225...",11428.571429
99999,MID242000,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,JJN,80000,"{'Initial Investment': '$80,000.00', 'Expected...","[{'Initial Investment': '$80,000.00', 'Expecte...","[354323206.4, 2133278064.0, 246043500.0, 1.225...",11428.571429
99999,MID242000,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,ABC,80000,"{'Initial Investment': '$80,000.00', 'Expected...","[{'Initial Investment': '$80,000.00', 'Expecte...","[354323206.4, 2133278064.0, 246043500.0, 1.225...",11428.571429

In [28]:
# Save only the 'PORTFOLIO' and 'INITIAL_INVESTMENT_STOCKS' columns to a new CSV file
df_exploded[['PORTFOLIO', 'INITIAL_INVESTMENT_STOCKS', 'MEMBER_ID']].to_csv('PROTFOLIO.csv', index=False)

In [37]:
# Function to extract specific fields from ORG_INVST column
def extract_org_invst_details(org_invst_str):
    org_invst_dict = ast.literal_eval(org_invst_str)
    return pd.Series({
        'EXPECTED_FINAL_PORTFOLIO_VALUE': org_invst_dict.get('Expected Final Portfolio Value'),
        'Median_Final_Portfolio_Value': org_invst_dict.get('Median Final Portfolio Value'),
        'STANDARD_DEVIATION_OF_FINAL_PORTFOLIO_VALUE': org_invst_dict.get('Standard Deviation of Final Portfolio Value'),
        'VALUE_AT_RISK': org_invst_dict.get('Value at Risk (VaR 95%)'),
        'Conditional_Value_at_Risk': org_invst_dict.get('Conditional Value at Risk (CVaR 95%)'),
        'PROBABILITY_OF_LOSS': org_invst_dict.get('Probability of Loss'),
        'SHARPE_RATIO': org_invst_dict.get('Sharpe Ratio')
    })

# Apply the function to the ORG_INVST column and join with the exploded DataFrame
org_invst_details = df['ORG_INVST'].apply(extract_org_invst_details)
df_final = df_exploded.join(org_invst_details)

# Select only the required columns
df_selected = df_final[['MEMBER_ID', 'PORTFOLIO', 'MEMBER_NAME', 'MEMBER_DOB', 'MEMBER_EMPLOYMENT', 'MEMBER_GENDER', 'MEMBER_CITY_TOWN', 'MEMBER_STATE', 'MEMBER_CONTACT_VERIFIED', 'INITIAL_INVESTMENT_STOCKS', 'EXPECTED_FINAL_PORTFOLIO_VALUE', 'STANDARD_DEVIATION_OF_FINAL_PORTFOLIO_VALUE', 'VALUE_AT_RISK', 'PROBABILITY_OF_LOSS', 'SHARPE_RATIO']]

In [38]:
# Write the DataFrame to a CSV file with column names
df_selected.to_csv('ORIGINAL_INVESTMENT_DETAILS.csv', index=False, header=True)

In [47]:
# Function to extract specific fields from TEMP_OPTIMIZED column
def extract_temp_opti_details(temp_opti_str):
    temp_optimized_list = ast.literal_eval(temp_opti_str)
    if isinstance(temp_optimized_list, list) and len(temp_optimized_list) > 0:
        temp_optimized_dict = temp_optimized_list[0]  # Assuming the first element is the dictionary we need
        return pd.Series({
            'OPTIMIZED_EXPECTED_FINAL_PORTFOLIO_VALUE': temp_optimized_dict.get('Expected Final Portfolio Value'),
            'OPTIMIZED_MEDIAN_FINAL_PORTFOLIO_VALUE': temp_optimized_dict.get('Median Final Portfolio Value'),
            'OPTIMIZED_STANDARD_DEVIATION_OF_FINAL_PORTFOLIO_VALUE': temp_optimized_dict.get('Standard Deviation of Final Portfolio Value'),
            'OPTIMIZED_VALUE_AT_RISK': temp_optimized_dict.get('Value at Risk (VaR 95%'),
            'OPTIMIZED_CONDITIONAL_VALUE_AT_RISK': temp_optimized_dict.get('Conditional Value at Risk (CVaR 95%'),
            'OPTIMIZED_PROBABILITY_OF_LOSS': temp_optimized_dict.get('Probability of Loss'),
            'OPTIMIZED_SHARPE_RATIO': temp_optimized_dict.get('Sharpe Ratio')
        })
    else:
        return pd.Series({
            'OPTIMIZED_EXPECTED_FINAL_PORTFOLIO_VALUE': None,
            'OPTIMIZED_MEDIAN_FINAL_PORTFOLIO_VALUE': None,
            'OPTIMIZED_STANDARD_DEVIATION_OF_FINAL_PORTFOLIO_VALUE': None,
            'OPTIMIZED_VALUE_AT_RISK': None,
            'OPTIMIZED_CONDITIONAL_VALUE_AT_RISK': None,
            'OPTIMIZED_PROBABILITY_OF_LOSS': None,
            'OPTIMIZED_SHARPE_RATIO': None
        })

# Apply the function to the TEMP_OPTIMIZED column and join with the exploded DataFrame
temp_opti_details = df['TEMP_OPTIMIZED'].apply(extract_temp_opti_details)
df_final = df_exploded.join(temp_opti_details)

# Select only the required columns
df_selected = df_final[['MEMBER_ID', 'PORTFOLIO', 
                        'OPTIMIZED_EXPECTED_FINAL_PORTFOLIO_VALUE', 
                        'OPTIMIZED_MEDIAN_FINAL_PORTFOLIO_VALUE',
                        'OPTIMIZED_STANDARD_DEVIATION_OF_FINAL_PORTFOLIO_VALUE', 
                        'OPTIMIZED_VALUE_AT_RISK', 
                        'OPTIMIZED_CONDITIONAL_VALUE_AT_RISK', 
                        'OPTIMIZED_PROBABILITY_OF_LOSS', 
                        'OPTIMIZED_SHARPE_RATIO']]

# Save the selected columns to a new CSV file
df_selected.to_csv('optimized_portfolio_details.csv', index=False)

In [1]:
import json
from portfolio import Portfolio
from optimizer import PortfolioOptimizer
from simulations import MonteCarloSimulation
from utils import (
    get_simulation_insights,
    display_optimal_weights
)

#Snowpark lib
from snowflake.snowpark import Session
import pandas as pd
from fosforml.model_manager.snowflakesession import get_session
my_session = get_session()

config = {
    "TICKERS" : [], "START_DATE" : '2020-01-01', "END_DATE" : '2023-01-01', "INITIAL_INVESTMENT" : 100000,
    "NUM_SIMULATIONS" : 500, "TIME_HORIZON" : 252, "RISK_FREE_RATE" : 0.02, "WEIGHTS" : None, "OPTIMIZE" : True, "BALANCED" : False
}

In [2]:
table_name = 'STOCKS_DATA'
sf_df = my_session.sql("select * from {}".format(table_name))
df = sf_df.to_pandas()

In [3]:
def load_data(df, tickers: list):
    stock_data = {}
    min_len = []
    for ticker in tickers:
        data = df[df["STOCK"] == ticker]
        stock_data[ticker] = list(data["ADJ_CLOSE"])
        min_len.append(len(data))
    last_len = min(min_len)
    for ticker in tickers:
        stock_data[ticker] = stock_data[ticker][:last_len]
    
    stock_data = pd.DataFrame(stock_data)
    return stock_data

In [7]:
def main(config=config):
    # Extract configuration parameters
    tickers = config.get('TICKERS', ["MTFS", "ALPA", "OOGGL"])
    start_date = config.get('START_DATE')
    end_date = config.get('END_DATE')
    initial_investment = config.get('INITIAL_INVESTMENT', 1000)
    num_simulations = config.get('NUM_SIMULATIONS', 10000)
    time_horizon = config.get('TIME_HORIZON', 252)
    risk_free_rate = config.get('RISK_FREE_RATE', 0.0)
    custom_weights = config.get('WEIGHTS')
    optimization_config = config.get('optimization', {})
    optimize = optimization_config.get('OPTIMIZE', True)
    balanced = optimization_config.get('BALANCED', False)

In [8]:
    # Load data
stock_data = load_data(df, tickers)
# Create portfolio
portfolio = Portfolio(stock_data)
portfolio.calculate_returns()

NameError: name 'tickers' is not defined

In [10]:
def main(config=config):
    
    # Extract configuration parameters
    tickers = config.get('TICKERS', ["MTFS", "ALPA", "OOGGL"])
    start_date = config.get('START_DATE')
    end_date = config.get('END_DATE')
    initial_investment = config.get('INITIAL_INVESTMENT', 1000)
    num_simulations = config.get('NUM_SIMULATIONS', 10000)
    time_horizon = config.get('TIME_HORIZON', 252)
    risk_free_rate = config.get('RISK_FREE_RATE', 0.0)
    custom_weights = config.get('WEIGHTS')
    optimization_config = config.get('optimization', {})
    optimize = optimization_config.get('OPTIMIZE', True)
    balanced = optimization_config.get('BALANCED', False)
    # Load data
    stock_data = load_data(df, tickers)
    
    # Create portfolio
    portfolio = Portfolio(stock_data)
    portfolio.calculate_returns()
    
    # Annualize returns and covariance
    expected_returns = portfolio.returns.mean() * 252
    covariance_matrix = portfolio.returns.cov() * 252

    # return covariance_matrix, expected_returns
    
    # Determine weights
    if optimize:
        optimizer = PortfolioOptimizer(
            expected_returns,
            covariance_matrix,
            risk_free_rate=risk_free_rate
        )
        if balanced:
            optimal_weights = optimizer.minimize_volatility(target_return=expected_returns.mean())
            # print("\nOptimal Balanced Portfolio Weights:")
        else:
            optimal_weights = optimizer.maximize_sharpe_ratio()
            # print("\nOptimal Portfolio Weights to Maximize Sharpe Ratio:")
        display_optimal_weights(stock_data.columns, optimal_weights)
        weights = optimal_weights
    elif custom_weights:
        weights = custom_weights
        # print("\nUsing Custom Weights:")
        display_optimal_weights(stock_data.columns, weights)
    else:
        num_assets = len(expected_returns)
        weights = [1.0 / num_assets] * num_assets
        # print("\nUsing Equal Weights:")
        # display_optimal_weights(stock_data.columns, weights)

    # print(weights)
    # Perform Monte Carlo Simulation
    simulation = MonteCarloSimulation(portfolio.returns, initial_investment, weights)
    all_cumulative_returns, final_portfolio_values = simulation.run_simulation(
        num_simulations, time_horizon
    )
    
    # Analyze Results
    final_insights = get_simulation_insights(final_portfolio_values, initial_investment)
    # print("**************************")
    # for k, v in final_insights.items():
    #     print(k,":", v)
    # print(final_insights)
    return all_cumulative_returns, final_portfolio_values

In [12]:
def optimied_sharpe(config=config):
    # Extract configuration parameters
    tickers = config.get('TICKERS', ["MTFS", "ALPA", "OOGGL"])
    start_date = config.get('START_DATE')
    end_date = config.get('END_DATE')
    initial_investment = config.get('INITIAL_INVESTMENT', 1000)
    num_simulations = config.get('NUM_SIMULATIONS', 10000)
    time_horizon = config.get('TIME_HORIZON', 252)
    risk_free_rate = config.get('RISK_FREE_RATE', 0.0)
    custom_weights = config.get('WEIGHTS')
    optimization_config = config.get('optimization', {})
    optimize = optimization_config.get('OPTIMIZE', True)
    balanced = optimization_config.get('BALANCED', False)
    
    # Load data
    stock_data = load_data(df, tickers)
    
    # Create portfolio
    portfolio = Portfolio(stock_data)
    portfolio.calculate_returns()
    
    # Annualize returns and covariance
    expected_returns = portfolio.returns.mean() * 252
    covariance_matrix = portfolio.returns.cov() * 252
    
    # Determine weights
    if optimize:
        optimizer = PortfolioOptimizer(
            expected_returns,
            covariance_matrix,
            risk_free_rate=risk_free_rate
        )
        optimal_weights = optimizer.maximize_sharpe_ratio()
        weights = optimal_weights
    
    simulation = MonteCarloSimulation(portfolio.returns, initial_investment, weights)
    all_cumulative_returns, final_portfolio_values = simulation.run_simulation(
        num_simulations, time_horizon
    )
    
    final_insights = get_simulation_insights(final_portfolio_values, initial_investment)
    return final_insights, weights

In [13]:
import random
from tqdm import tqdm
tqdm.pandas()

def modify_config(tickers, initial):
    config["TICKERS"] = tickers
    config["INITIAL_INVESTMENT"] = initial
    r1, r2 = optimied_sharpe(config)
    r2 = r2 * initial
    if len(r2) != len(tickers):
        raise ValueError("Mismatch between number of tickers and expected portfolio values")
    return [r1, r2]

In [14]:
# Load user data
table_name = 'MEMBER_MASTER'
users_df = my_session.sql("select * from {}".format(table_name))
users = users_df.to_pandas()
users = users.head(50000)

In [15]:
# Generate portfolios
stocks = list(df["STOCK"].unique())
portfolio_stocks = [2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 8, 9]
portfolio = [random.sample(stocks, random.choice(portfolio_stocks)) for i in range(users.shape[0])]

users["PORTFOLIO"] = portfolio
users["INITIAL_INVESTMENT"] = users["MEMBER_ID"].apply(lambda x: random.choice([1000, 10000, 5000, 50000, 1000000, 80000, 90000, 11000, 45000, 55000, 1000000, 40000, 88000, 97000, 49000, 69000]))

In [ ]:
# Apply configuration modification
users["ORG_INVST"] = users[["PORTFOLIO", "INITIAL_INVESTMENT"]].progress_apply(lambda x: modify_config(x[0], x[1]), axis=1)
users.to_csv("interminnet_data1.csv", index=False)

# Repeat for second batch of users
users2 = users.tail(50000)
portfolio = [random.sample(stocks, random.choice(portfolio_stocks)) for i in range(users2.shape[0])]
users2["PORTFOLIO"] = portfolio
users2["INITIAL_INVESTMENT"] = users2["MEMBER_ID"].apply(lambda x: random.choice([1000, 10000, 5000, 50000, 1000000, 80000, 90000, 11000, 45000, 55000, 1000000, 40000, 88000, 97000, 49000, 69000]))

 21%|██▏       | 10673/50000 [21:15<1:20:11,  8.17it/s]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

 46%|████▌     | 22807/50000 [45:32<50:22,  9.00it/s]  IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

 95%|█████████▌| 47530/50000 [1:35:05<04:35,  8.97it/s]

In [2]:
table_name = 'ORIGINAL_INVESTMENT_DETAILS'
sf_df = my_session.sql("select * from {}".format(table_name))
df = sf_df.to_pandas()

In [3]:
df

,MEMBER_ID,PORTFOLIO,MEMBER_NAME,MEMBER_DOB,MEMBER_EMPLOYMENT,MEMBER_GENDER,MEMBER_CITY_TOWN,MEMBER_STATE,MEMBER_CONTACT_VERIFIED,INITIAL_INVESTMENT_STOCKS,EXPECTED_FINAL_PORTFOLIO_VALUE,STANDARD_DEVIATION_OF_FINAL_PORTFOLIO_VALUE,VALUE_AT_RISK,PROBABILITY_OF_LOSS,SHARPE_RATIO
0,MID000001,CCSO,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,1250.00,"$6,276.49","$1,375.97",$723.77,16.20%,0.9277
1,MID000001,MPJ,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,1250.00,"$6,276.49","$1,375.97",$723.77,16.20%,0.9277
2,MID000001,ABC,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,1250.00,"$6,276.49","$1,375.97",$723.77,16.20%,0.9277
3,MID000001,EG,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,1250.00,"$6,276.49","$1,375.97",$723.77,16.20%,0.9277
4,MID000002,EG,Jade Strassner,1986-11-19,Curtin University,Female,Gladstone,Queensland,False,7666.67,"$85,991.79","$18,111.73","$9,837.59",17.40%,0.9382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516861,MID242000,MZNA,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,11428.57,"$97,742.84","$19,765.55","$10,996.07",18.40%,0.8977
516862,MID242000,EPF,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,11428.57,"$97,742.84","$19,765.55","$10,996.07",18.40%,0.8977
516863,MID242000,HD,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,11428.57,"$97,742.84","$19,765.55","$10,996.07",18.40%,0.8977
516864,MID242000,JJN,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,11428.57,"$97,742.84","$19,765.55","$10,996.07",18.40%,0.8977
516865,MID242000,ABC,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,11428.57,"$97,742.84","$19,765.55","$10,996.07",18.40%,0.8977

In [4]:
# Define the comprehensive mapping for Category and Sub-Category
category_mapping = {
    'CCSO': ('Energy', 'Oil and Gas Exploration & Production'),
    'MPJ': ('Materials', 'Chemicals'),
    'ABC': ('Industrials', 'Aerospace & Defense'),
    'EG': ('Consumer Discretionary', 'Auto Components'),
    'FWC': ('Consumer Staples', 'Food & Staples Retailing'),
    'ONH': ('Health Care', 'Biotechnology'),
    'MZNA': ('Financials', 'Banks'),
    'GMNA': ('Information Technology', 'IT Services'),
    'TCA': ('Communication Services', 'Diversified Telecommunication Services'),
    'OCST': ('Utilities', 'Electric Utilities'),
    'ALPA': ('Real Estate', 'Equity Real Estate Investment Trusts (REITs)'),
    'KRM': ('Industrials', 'Machinery'),
    'JJN': ('Consumer Discretionary', 'Retailing'),
    'NEK': ('Materials', 'Metals & Mining'),
    'DMC': ('Health Care', 'Pharmaceuticals'),
    'HD': ('Consumer Staples', 'Beverages'),
    'EPF': ('Financials', 'Insurance'),
    'LTSA': ('Information Technology', 'Software'),
    'PEP': ('Communication Services', 'Media'),
    'SM': ('Utilities', 'Gas Utilities'),
    'OOGGL': ('Real Estate', 'Real Estate Management & Development'),
    'PG': ('Consumer Discretionary', 'Hotels, Restaurants & Leisure'),
    'NTIC': ('Industrials', 'Construction & Engineering'),
    'MTFS': ('Information Technology', 'Technology Hardware, Storage & Peripherals'),
    'ABT': ('Health Care', 'Health Care Equipment & Supplies'),
    'OK': ('Communication Services', 'Entertainment'),
    'TWM': ('Utilities', 'Water Utilities'),
    'GS': ('Materials', 'Paper & Forest Products'),
    'MMM': ('Industrials', 'Industrial Conglomerates')
    # Add more mappings as needed
}

# Define the comprehensive mapping for Cap Side
cap_side_mapping = {
    'CCSO': 'Mega Cap',
    'MPJ': 'Large Cap',
    'ABC': 'Mid Cap',
    'EG': 'Small Cap',
    'FWC': 'Micro Cap',
    'ONH': 'Nano Cap',
    'MZNA': 'Mega Cap',
    'GMNA': 'Large Cap',
    'TCA': 'Mid Cap',
    'OCST': 'Small Cap',
    'ALPA': 'Micro Cap',
    'KRM': 'Mid Cap',
    'JJN': 'Small Cap',
    'NEK': 'Large Cap',
    'DMC': 'Micro Cap',
    'HD': 'Nano Cap',
    'EPF': 'Mega Cap',
    'LTSA': 'Large Cap',
    'PEP': 'Mid Cap',
    'SM': 'Small Cap',
    'OOGGL': 'Micro Cap',
    'PG': 'Mid Cap',
    'NTIC': 'Large Cap',
    'MTFS': 'Mid Cap',
    'ABT': 'Small Cap',
    'OK': 'Micro Cap',
    'TWM': 'Nano Cap',
    'GS': 'Large Cap',
    'MMM': 'Mid Cap'
    # Add more mappings as needed
}

# Add Category and Sub-Category columns
df['Category'] = df['PORTFOLIO'].map(lambda x: category_mapping.get(x, ('Unknown', 'Unknown'))[0])
df['Sub-Category'] = df['PORTFOLIO'].map(lambda x: category_mapping.get(x, ('Unknown', 'Unknown'))[1])

# Add Cap Side column
df['Cap Side'] = df['PORTFOLIO'].map(lambda x: cap_side_mapping.get(x, 'Unknown'))

# Generate date range for 3 years with the 1st of every month
start_date = datetime(2021, 1, 1)
end_date = datetime(2024, 1, 1)
date_range = pd.date_range(start=start_date, end=end_date, freq='MS')

# Assign dates to the dataset
df['Date'] = np.tile(date_range, int(np.ceil(len(df) / len(date_range))))[:len(df)]

# Save the updated dataset
df.to_csv('updated_investment_details.csv', index=False)

NameError: name 'datetime' is not defined

In [1]:
import json
from portfolio import Portfolio
from optimizer import PortfolioOptimizer
from simulations import MonteCarloSimulation
from utils import (
    get_simulation_insights,
    display_optimal_weights
)

# Snowpark lib
from snowflake.snowpark import Session
import pandas as pd
from fosforml.model_manager.snowflakesession import get_session
my_session = get_session()

config = {
    "TICKERS": [], "START_DATE": '2020-01-01', "END_DATE": '2023-01-01', "INITIAL_INVESTMENT": 100000,
    "NUM_SIMULATIONS": 500, "TIME_HORIZON": 252, "RISK_FREE_RATE": 0.02, "WEIGHTS": None, "OPTIMIZE": True, "BALANCED": False
}

In [2]:
table_name = 'STOCKS_DATA'
sf_df = my_session.sql("select * from {}".format(table_name))
df = sf_df.to_pandas()
tickers = ["MTFS", "ALPA", "TCA", "NTIC", 'MZNA', 'EG', 'HD']
config["TICKERS"] = tickers

In [3]:
def load_data(df, tickers: list):
    stock_data = {}
    min_len = []
    for ticker in tickers:
        data = df[df["STOCK"] == ticker]
        stock_data[ticker] = list(data["ADJ_CLOSE"])
        min_len.append(len(data))
    last_len = min(min_len)
    for ticker in tickers:
        stock_data[ticker] = stock_data[ticker][:last_len]
    
    stock_data = pd.DataFrame(stock_data)
    return stock_data

def main(config=config):
    # Extract configuration parameters
    tickers = config.get('TICKERS', ["MTFS", "ALPA", "OOGGL"])
    start_date = config.get('START_DATE')
    end_date = config.get('END_DATE')
    initial_investment = config.get('INITIAL_INVESTMENT', 1000)
    num_simulations = config.get('NUM_SIMULATIONS', 10000)
    time_horizon = config.get('TIME_HORIZON', 252)
    risk_free_rate = config.get('RISK_FREE_RATE', 0.0)
    custom_weights = config.get('WEIGHTS')
    optimization_config = config.get('optimization', {})
    optimize = optimization_config.get('OPTIMIZE', True)
    balanced = optimization_config.get('BALANCED', False)

In [4]:

    # Load data
    stock_data = load_data(df, tickers)
    
    # Create portfolio
    portfolio = Portfolio(stock_data)
    portfolio.calculate_returns()
    
    # Annualize returns and covariance
    expected_returns = portfolio.returns.mean() * 252
    covariance_matrix = portfolio.returns.cov() * 252

In [ ]:

    # Load data
    stock_data = load_data(df, tickers)
    
    # Create portfolio
    portfolio = Portfolio(stock_data)
    portfolio.calculate_returns()
    
    # Annualize returns and covariance
    expected_returns = portfolio.returns.mean() * 252
    covariance_matrix = portfolio.returns.cov() * 252
    
    # Determine weights
    if optimize:
        optimizer = PortfolioOptimizer(
            expected_returns,
            covariance_matrix,
            risk_free_rate=risk_free_rate
        )
        if balanced:
            optimal_weights = optimizer.minimize_volatility(target_return=expected_returns.mean())
        else:
            optimal_weights = optimizer.maximize_sharpe_ratio()
        display_optimal_weights(stock_data.columns, optimal_weights)
        weights = optimal_weights
    elif custom_weights:
        weights = custom_weights
        display_optimal_weights(stock_data.columns, weights)
    else:
        num_assets = len(expected_returns)
        weights = [1.0 / num_assets] * num_assets

    # Perform Monte Carlo Simulation
    simulation = MonteCarloSimulation(portfolio.returns, initial_investment, weights)
    all_cumulative_returns, final_portfolio_values = simulation.run_simulation(
        num_simulations, time_horizon
    )
    
    # Analyze Results
    final_insights = get_simulation_insights(final_portfolio_values, initial_investment)
    return all_cumulative_returns, final_portfolio_values

def original(config):
    tickers = config.get('TICKERS', ["MTFS", "ALPA", "OOGGL"])
    start_date = config.get('START_DATE')
    end_date = config.get('END_DATE')
    initial_investment = config.get('INITIAL_INVESTMENT', 1000)
    num_simulations = config.get('NUM_SIMULATIONS', 10000)
    time_horizon = config.get('TIME_HORIZON', 252)
    risk_free_rate = config.get('RISK_FREE_RATE', 0.0)
    custom_weights = config.get('WEIGHTS')
    optimization_config = config.get('optimization', {})
    optimize = optimization_config.get('OPTIMIZE', True)
    balanced = optimization_config.get('BALANCED', False)
    
    # Load data
    stock_data = load_data(df, tickers)

    # Create portfolio
    num_assets = len(tickers)
    portfolio = Portfolio(stock_data)
    portfolio.calculate_returns()
    weights = num_assets * [1.0 / num_assets]
    simulation = MonteCarloSimulation(portfolio.returns, initial_investment, weights)
    all_cumulative_returns, final_portfolio_values = simulation.run_simulation(
        num_simulations, time_horizon
    )
    
    # Analyze Results
    final_insights = get_simulation_insights(final_portfolio_values, initial_investment)
    return final_insights

def optimied_sharpe(config=config):
    # Extract configuration parameters
    tickers = config.get('TICKERS', ["MTFS", "ALPA", "OOGGL"])
    start_date = config.get('START_DATE')
    end_date = config.get('END_DATE')
    initial_investment = config.get('INITIAL_INVESTMENT', 1000)
    num_simulations = config.get('NUM_SIMULATIONS', 10000)
    time_horizon = config.get('TIME_HORIZON', 252)
    risk_free_rate = config.get('RISK_FREE_RATE', 0.0)
    custom_weights = config.get('WEIGHTS')
    optimization_config = config.get('optimization', {})
    optimize = optimization_config.get('OPTIMIZE', True)
    balanced = optimization_config.get('BALANCED', False)
    
    # Load data
    stock_data = load_data(df, tickers)
    
    # Create portfolio
    portfolio = Portfolio(stock_data)
    portfolio.calculate_returns()
    
    # Annualize returns and covariance
    expected_returns = portfolio.returns.mean() * 252
    covariance_matrix = portfolio.returns.cov() * 252
    
    # Determine weights
    if optimize:
        optimizer = PortfolioOptimizer(
            expected_returns,
            covariance_matrix,
            risk_free_rate=risk_free_rate
        )
        optimal_weights = optimizer.maximize_sharpe_ratio()
        weights = optimal_weights
    
    simulation = MonteCarloSimulation(portfolio.returns, initial_investment, weights)
    all_cumulative_returns, final_portfolio_values = simulation.run_simulation(
        num_simulations, time_horizon
    )
    
    final_insights = get_simulation_insights(final_portfolio_values, initial_investment)
    return final_insights, weights

import random
from tqdm import tqdm
tqdm.pandas()

def modify_config(tickers, initial):
    config["TICKERS"] = tickers
    config["INITIAL_INVESTMENT"] = initial
    r1, r2 = optimied_sharpe(config)
    r2 = r2 * initial
    if len(r2) != len(tickers):
        raise ValueError("Mismatch between number of tickers and expected portfolio values")
    return [r1, r2]

# Load user data
table_name = 'MEMBER_MASTER'
users_df = my_session.sql("select * from {}".format(table_name))
users = users_df.to_pandas()
users = users.head(50000)

# Generate portfolios
stocks = list(df["STOCK"].unique())
portfolio_stocks = [2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 8, 9]
portfolio = [random.sample(stocks, random.choice(portfolio_stocks)) for i in range(users.shape[0])]

users["PORTFOLIO"] = portfolio
users["INITIAL_INVESTMENT"] = users["MEMBER_ID"].apply(lambda x: random.choice([1000, 10000, 5000, 50000, 1000000, 80000, 90000, 11000, 45000, 55000, 1000000, 40000, 88000, 97000, 49000, 69000]))

# Apply configuration modification
users["ORG_INVST"] = users[["PORTFOLIO", "INITIAL_INVESTMENT"]].progress_apply(lambda x: modify_config(x[0], x[1]), axis=1)

# Extract expected portfolio values and create a new column
users["EXPECTED_PORTFOLIO"] = users["ORG_INVST"].apply(lambda x: x[1])

# Save the first batch of user data to a new CSV file
users.to_csv("interminnet_data1.csv", index=False)

# Repeat for second batch of users
users2 = users.tail(50000)
portfolio = [random.sample(stocks, random.choice(portfolio_stocks)) for i in range(users2.shape[0])]
users2["PORTFOLIO"] = portfolio