In [14]:
import json
import pandas as pd
from fosforml.model_manager.snowflakesession import get_session
my_session = get_session()

In [30]:
table_name = 'FINAL_DATA'
sf_df = my_session.sql("select * from {}".format(table_name))
df = sf_df.to_pandas()

In [31]:
df

,MEMBER_ID,MEMBER_NAME,MEMBER_DOB,MEMBER_EMPLOYMENT,MEMBER_GENDER,MEMBER_CITY_TOWN,MEMBER_STATE,MEMBER_CONTACT_VERIFIED,PORTFOLIO,INTITIAL_INVVESTMENT,ORG_INVST,TEMP_OPTIMIZED,EXPECTED_PORTFOLIO,INITIAL_INVESTMENT_STOCKS
0,MID000001,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,"['CCSO', 'MPJ', 'ABC', 'EG']",5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...","[1250.0, 1250.0, 1250.0, 1250.0]"
1,MID000002,Jade Strassner,1986-11-19,Curtin University,Female,Gladstone,Queensland,False,"['EG', 'ABC', 'ONH', 'MZNA', 'FWC', 'GMNA', 'T...",69000,"{'Initial Investment': '$69,000.00', 'Expected...","[{'Initial Investment': '$69,000.00', 'Expecte...","[263583247.83, 1586958889.8, 183033297.12, 9.1...","[7666.666666666667, 7666.666666666667, 7666.66..."
2,MID000003,Mari Candlish,1989-01-27,University of New England,Female,Walgett,New South Wales,True,"['MMM', 'PG', 'NTIC', 'EPF', 'SM', 'ALPA']",49000,"{'Initial Investment': '$49,000.00', 'Expected...","[{'Initial Investment': '$49,000.00', 'Expecte...","[132926565.44999999, 800312599.8000001, 923047...","[8166.666666666667, 8166.666666666667, 8166.66..."
3,MID000004,Serina Leto,1984-03-08,Griffith University,Female,Paynesville,Victoria,True,"['JJN', 'PG', 'AB', 'OOGGL', 'NTIC', 'MMM']",1000,"{'Initial Investment': '$1,000.00', 'Expected ...","[{'Initial Investment': '$1,000.00', 'Expected...","[55363.001, 333324.69800000003, 38444.2969, 1....","[166.66666666666666, 166.66666666666666, 166.6..."
4,MID000005,Brett Butzen,1970-01-23,La Trobe University,Male,Palmerston,Northern Territory,True,"['SM', 'JJN', 'ALPA', 'NTIC', 'HD', 'AB', 'MZNA']",5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...","[714.2857142857143, 714.2857142857143, 714.285..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,MID241996,Nu Ragel,1967-01-24,La Trobe University,Male,Urraween,Queensland,False,"['MTFS', 'MPJ', 'SM', 'OCST', 'NTIC', 'CCSO', ...",90000,"{'Initial Investment': '$90,000.00', 'Expected...","[{'Initial Investment': '$90,000.00', 'Expecte...","[448440308.09999996, 2699930052.0, 311398804.8...","[11250.0, 11250.0, 11250.0, 11250.0, 11250.0, ..."
99996,MID241997,Lucy Hoa,1973-04-30,University of New England,Male,Wilton,New South Wales,True,"['GS', 'JJN', 'HD']",5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...","[1666.6666666666667, 1666.6666666666667, 1666...."
99997,MID241998,Lucina Klimek,1991-07-03,Queensland University of Technology,Male,Vincentia,New South Wales,False,"['ONH', 'AB', 'GS']",1000,"{'Initial Investment': '$1,000.00', 'Expected ...","[{'Initial Investment': '$1,000.00', 'Expected...","[55363.001, 333324.69800000003, 38444.2969, 1....","[333.3333333333333, 333.3333333333333, 333.333..."
99998,MID241999,Maurine Dopico,1976-05-17,RMIT University,Male,Eden,New South Wales,False,"['MPJ', 'MZNA', 'FWC', 'HD', 'ALPA', 'OOGGL']",5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...","[833.3333333333334, 833.3333333333334, 833.333..."
99999,MID242000,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,"['MMM', 'PG', 'MZNA', 'EPF', 'HD', 'JJN', 'ABC']",80000,"{'Initial Investment': '$80,000.00', 'Expected...","[{'Initial Investment': '$80,000.00', 'Expecte...","[354323206.4, 2133278064.0, 246043500.0, 1.225...","[11428.57142857143, 11428.57142857143, 11428.5..."

In [32]:
import ast
# Function to explode the 'PORTFOLIO' and 'INITIAL_INVESTMENT_STOCKS' columns
def explode_columns(df, portfolio_col, investment_col):
    df[portfolio_col] = df[portfolio_col].apply(eval)  # Convert string representation of list to actual list
    df[investment_col] = df[investment_col].apply(eval)  # Convert string representation of list to actual list
    df = df.explode([portfolio_col, investment_col])
    return df

# Columns to be exploded
portfolio_col = 'PORTFOLIO'
investment_col = 'INITIAL_INVESTMENT_STOCKS'

# Explode the specified columns
df_exploded = explode_columns(df, portfolio_col, investment_col)

In [33]:
df_exploded

,MEMBER_ID,MEMBER_NAME,MEMBER_DOB,MEMBER_EMPLOYMENT,MEMBER_GENDER,MEMBER_CITY_TOWN,MEMBER_STATE,MEMBER_CONTACT_VERIFIED,PORTFOLIO,INTITIAL_INVVESTMENT,ORG_INVST,TEMP_OPTIMIZED,EXPECTED_PORTFOLIO,INITIAL_INVESTMENT_STOCKS
0,MID000001,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,CCSO,5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...",1250.0
0,MID000001,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,MPJ,5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...",1250.0
0,MID000001,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,ABC,5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...",1250.0
0,MID000001,Vallie Bachman,1980-01-08,The University of Sydney,Female,Hobart,Tasmania,False,EG,5000,"{'Initial Investment': '$5,000.00', 'Expected ...","[{'Initial Investment': '$5,000.00', 'Expected...","[1384075.025, 8333117.45, 961107.42, 4.7874302...",1250.0
1,MID000002,Jade Strassner,1986-11-19,Curtin University,Female,Gladstone,Queensland,False,EG,69000,"{'Initial Investment': '$69,000.00', 'Expected...","[{'Initial Investment': '$69,000.00', 'Expecte...","[263583247.83, 1586958889.8, 183033297.12, 9.1...",7666.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99999,MID242000,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,MZNA,80000,"{'Initial Investment': '$80,000.00', 'Expected...","[{'Initial Investment': '$80,000.00', 'Expecte...","[354323206.4, 2133278064.0, 246043500.0, 1.225...",11428.571429
99999,MID242000,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,EPF,80000,"{'Initial Investment': '$80,000.00', 'Expected...","[{'Initial Investment': '$80,000.00', 'Expecte...","[354323206.4, 2133278064.0, 246043500.0, 1.225...",11428.571429
99999,MID242000,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,HD,80000,"{'Initial Investment': '$80,000.00', 'Expected...","[{'Initial Investment': '$80,000.00', 'Expecte...","[354323206.4, 2133278064.0, 246043500.0, 1.225...",11428.571429
99999,MID242000,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,JJN,80000,"{'Initial Investment': '$80,000.00', 'Expected...","[{'Initial Investment': '$80,000.00', 'Expecte...","[354323206.4, 2133278064.0, 246043500.0, 1.225...",11428.571429
99999,MID242000,Cathrine Cousey,1987-06-09,The University of Newcastle,Male,Moss Vale,New South Wales,True,ABC,80000,"{'Initial Investment': '$80,000.00', 'Expected...","[{'Initial Investment': '$80,000.00', 'Expecte...","[354323206.4, 2133278064.0, 246043500.0, 1.225...",11428.571429

In [28]:
# Save only the 'PORTFOLIO' and 'INITIAL_INVESTMENT_STOCKS' columns to a new CSV file
df_exploded[['PORTFOLIO', 'INITIAL_INVESTMENT_STOCKS', 'MEMBER_ID']].to_csv('PROTFOLIO.csv', index=False)

In [37]:
# Function to extract specific fields from ORG_INVST column
def extract_org_invst_details(org_invst_str):
    org_invst_dict = ast.literal_eval(org_invst_str)
    return pd.Series({
        'EXPECTED_FINAL_PORTFOLIO_VALUE': org_invst_dict.get('Expected Final Portfolio Value'),
        'Median_Final_Portfolio_Value': org_invst_dict.get('Median Final Portfolio Value'),
        'STANDARD_DEVIATION_OF_FINAL_PORTFOLIO_VALUE': org_invst_dict.get('Standard Deviation of Final Portfolio Value'),
        'VALUE_AT_RISK': org_invst_dict.get('Value at Risk (VaR 95%)'),
        'Conditional_Value_at_Risk': org_invst_dict.get('Conditional Value at Risk (CVaR 95%)'),
        'PROBABILITY_OF_LOSS': org_invst_dict.get('Probability of Loss'),
        'SHARPE_RATIO': org_invst_dict.get('Sharpe Ratio')
    })

# Apply the function to the ORG_INVST column and join with the exploded DataFrame
org_invst_details = df['ORG_INVST'].apply(extract_org_invst_details)
df_final = df_exploded.join(org_invst_details)

# Select only the required columns
df_selected = df_final[['MEMBER_ID', 'PORTFOLIO', 'INITIAL_INVESTMENT_STOCKS', 'EXPECTED_FINAL_PORTFOLIO_VALUE', 'STANDARD_DEVIATION_OF_FINAL_PORTFOLIO_VALUE', 'VALUE_AT_RISK', 'PROBABILITY_OF_LOSS', 'SHARPE_RATIO']]

In [38]:
# Write the DataFrame to a CSV file with column names
df_selected.to_csv('ORIGINAL_INVESTMENT_DETAILS.csv', index=False, header=True)

In [40]:
# Function to extract specific fields from ORG_INVST column
# Function to extract specific fields from TEMP_OPTIMIZED column
def extract_temp_opti_details(temp_opti_str):
    temp_optimized_dict = ast.literal_eval(temp_opti_str)
    return pd.Series({
        'OPTIMIZED_EXPECTED_FINAL_PORTFOLIO_VALUE': temp_optimized_dict.get('Expected Final Portfolio Value'),
        'OPTIMIZED_MEDIAN_FINAL_PORTFOLIO_VALUE': temp_optimized_dict.get('Median Final Portfolio Value'),
        'OPTIMIZED_STANDARD_DEVIATION_OF_FINAL_PORTFOLIO_VALUE': temp_optimized_dict.get('Standard Deviation of Final Portfolio Value'),
        'OPTIMIZED_VALUE_AT_RISK': temp_optimized_dict.get('Value at Risk (VaR 95%)'),
        'OPTIMIZED_CONDITIONAL_VALUE_AT_RISK': temp_optimized_dict.get('Conditional Value at Risk (CVaR 95%)'),
        'OPTIMIZED_PROBABILITY_OF_LOSS': temp_optimized_dict.get('Probability of Loss'),
        'OPTIMIZED_SHARPE_RATIO': temp_optimized_dict.get('Sharpe Ratio')
    })

# Apply the function to the TEMP_OPTIMIZED column and join with the exploded DataFrame
temp_opti_details = df['TEMP_OPTIMIZED'].apply(extract_temp_opti_details)
df_final = df.join(temp_opti_details)

# Select only the required columns
df_selected = df_final[['MEMBER_ID', 'OPTIMIZED_EXPECTED_FINAL_PORTFOLIO_VALUE', 'OPTIMIZED_MEDIAN_FINAL_PORTFOLIO_VALUE', 'OPTIMIZED_STANDARD_DEVIATION_OF_FINAL_PORTFOLIO_VALUE', 'OPTIMIZED_VALUE_AT_RISK', 'OPTIMIZED_CONDITIONAL_VALUE_AT_RISK', 'OPTIMIZED_PROBABILITY_OF_LOSS', 'OPTIMIZED_SHARPE_RATIO']]

# Save the selected columns to a new CSV file
df_selected.to_csv('optimized_portfolio_details.csv', index=False)

AttributeError: 'list' object has no attribute 'get'